name: Build package

on: workflow_call

jobs:
  build-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js and Yarn
        uses: ./.github/actions/node

      - name: Build package
        uses: ./.github/actions/build

      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: pkg-build-${{ github.run_id }}
          path: |
            build
            dist
