name: Run build pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**/*"

env:
  # Used by scripts/build-types.sh
  CI: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build application
        uses: ./.github/actions/build
